apiVersion: v1
kind: Namespace
metadata:
  name: postech

---
apiVersion: v1
kind: Secret
metadata:
  name: consulta-secret
  namespace: postech
data:
  DATABASE_URL: #{DATABASE_URL}#
  AWS_ACCESS_KEY_ID_B64: #{AWS_ACCESS_KEY_ID_B64}#
  AWS_SECRET_ACCESS_KEY_B64: #{AWS_SECRET_ACCESS_KEY_B64}#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consulta-config-map
  namespace: postech
data:
  AWS_REGION: "us-east-1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-deployment
  namespace: postech
  labels:
    app: consulta-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consulta-deployment
    spec:
      containers:
        - name: consulta-image
          image: #{CONSULTA_IMAGE}#
          ports:
            - containerPort: 3334
          envFrom:
            - secretRef:
                name: "consulta-secret"
            - configMapRef:
                name: "consulta-config-map"
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
  selector:
    matchLabels:
      app: consulta-deployment

---
apiVersion: v1
kind: Service
metadata:
  name: consulta-service
  namespace: postech
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: test
spec:
  ports:
    - port: 80
      targetPort: 3334
      protocol: TCP
  type: LoadBalancer
  selector:
    app: consulta-deployment

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consulta-hpa
  namespace: postech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consulta-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
