apiVersion: v1
kind: Namespace
metadata:
  name: postech

---
apiVersion: v1
kind: Secret
metadata:
  name: pos-tech-diner-consulta-secret
  namespace: postech
data:
  DATABASE_URL: #{DATABASE_URL}#
  AWS_ACCESS_KEY_ID_B64: #{AWS_ACCESS_KEY_ID_B64}#
  AWS_SECRET_ACCESS_KEY_B64: #{AWS_SECRET_ACCESS_KEY_B64}#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-tech-diner-consulta-config-map
  namespace: postech
data:
  AWS_REGION: "us-east-1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-tech-diner-consulta-deployment
  namespace: postech
  labels:
    app: pos-tech-diner-consulta-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pos-tech-diner-consulta-deployment
    spec:
      containers:
        - name: pos-tech-diner-consulta-image
          image: #{POS_TECH_DINER_CLIENTE_IMAGE}#
          ports:
            - containerPort: 3334
          envFrom:
            - secretRef:
                name: "pos-tech-diner-consulta-secret"
            - configMapRef:
                name: "pos-tech-diner-consulta-config-map"
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
  selector:
    matchLabels:
      app: pos-tech-diner-consulta-deployment

---
apiVersion: v1
kind: Service
metadata:
  name: pos-tech-diner-consulta-service
  namespace: postech
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: test
spec:
  ports:
    - port: 80
      targetPort: 3334
      protocol: TCP
  type: LoadBalancer
  selector:
    app: pos-tech-diner-consulta-deployment